modLoader="javafml"
loaderVersion="[${loader_version},)"
license="LGPL v2.1"

[[mods]]
modId="quartz"
version="${version}"
displayName="Quartz"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://biggerseries.net/"
# logoFile="examplemod.png"
authors="RogueLogix"
description='''
'''

[[dependencies.quartz]]
    modId="neoforge"
    required=true
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.quartz]]
    modId="minecraft"
    required=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.quartz]]
    modId="phosphophyllite"
required=true
    versionRange="${phos_version_range}"
    ordering="NONE"
    side="BOTH"

[features.quartz]
    openGLVersion = "[3.3,)"

[[mixins]]
    config="quartz.mixins.json"